### ISSUE TITLE
ingles everywhere

### ISSUE THREAD

**Issue by JoTerrance** [Zorben/ExamenServlet#1]
lo quiero todo en ingles
excepto el testo q muesta el navegador

jsp en ingles
nombres de ficheros en ingles
web.xml en ingles

**Comment by JoTerrance** [comment]
nombre de variables
nombre de metodos
nombres de clases
en ingles

**Comment by Zorben** [comment]
hecho

**Comment by JoTerrance** [comment]
no lo esta
aviso.jsp	Implementacion final del listado de idiomas/paises y borrado individual	3 days ago
datos.jsp	Implementado InsercionServlet	9 days ago
listado.jsp	Implementacion final del listado de idiomas/paises y borrado individual

**Comment by JoTerrance** [comment]
insercion borrado etc no esta en ingles

<servlet>
        <servlet-name>InsercionServlet</servlet-name>
        <servlet-class>es.salesianos.servlet.InsercionServlet</servlet-class>
    </servlet>

    <servlet-mapping>
        <servlet-name>InsercionServlet</servlet-name>
        <url-pattern>insercion</url-pattern>
    </servlet-mapping>
    
     <servlet>
        <servlet-name>BorradoServlet</servlet-name>
        <servlet-class>es.salesianos.servlet.BorradoServlet</servlet-class>
    </servlet>

    <servlet-mapping>
        <servlet-name>BorradoServlet</servlet-name>
        <url-pattern>borrado</url-pattern>
    </servlet-mapping>

**Comment by JoTerrance** [comment]
pageContext.setAttribute("idiomas", idiomas);
tampoco esta en ingles

lo quiero todo en ingles

**Comment by JoTerrance** [comment]
listarIdiomas()
ingles

**Comment by JoTerrance** [comment]
<input type="hidden" value="${param.id}" name="idborrar">
idBorrar borrar no es ingles

**Comment by JoTerrance** [comment]
utilidades.listaPaisesAString(

      <url-pattern>borrado</url-pattern>
