### ISSUE TITLE
la clase utilities no se usa con un new

### ISSUE THREAD

**Issue by JoTerrance** [Zorben/ExamenServlet#18]
listCountriesToString

**Comment by JoTerrance** [comment]
Utilities utilidades = new Utilities();
	for (Language lang : languages) {
		out.println("<tr>");
		out.println("<td style='text-align:center'>");
		out.println("<a href='warning.jsp?id="+lang.getId()+"'>x</a>");
		out.println("</td>");
		out.println("<td>");
		out.println(lang.getlanguageName());
		out.println("</td>");
		out.println("<td>");
		out.println(utilidades.listCountriesToString(service.searchCountriesByLang(lang)));

**Comment by JoTerrance** [comment]
el  new Utilities(); no te hace falta

**Comment by JoTerrance** [comment]
sigues teniendo 
private Utilities utilidades = new Utilities(); en el codigo 

ademas
	Utilities utilidades;
	for (Language lang : languages) {
		out.println("<tr>");
		out.println("<td style='text-align:center'>");
		out.println("<a href='warning.jsp?id="+lang.getId()+"'>x</a>");
		out.println("</td>");
		out.println("<td>");
		out.println(lang.getLanguageName());
		out.println("</td>");
		out.println("<td>");
		out.println(utilidades.listCountriesToString(service.searchCountriesByLang(lang)));


debe ser

	for (Language lang : languages) {
		out.println("<tr>");
		out.println("<td style='text-align:center'>");
		out.println("<a href='warning.jsp?id="+lang.getId()+"'>x</a>");
		out.println("</td>");
		out.println("<td>");
		out.println(lang.getLanguageName());
		out.println("</td>");
		out.println("<td>");
		out.println(Utilities.listCountriesToString(service.searchCountriesByLang(lang)));

**Comment by Zorben** [comment]
Uhm Yo no veo ese codigo que citas

https://github.com/Zorben/ExamenServlet/blob/master/ServletJsp/src/main/webapp/tablelist.jsp

2016-12-03 20:45 GMT+01:00 JoTerrance <notifications@github.com>:
