### ISSUE TITLE
a una clase de utilidades

### ISSUE THREAD

**Issue by JoTerrance** [Zorben/ExamenServlet#2]
public static String listaPaisesAString(List<Pais> lista){
			String cadena="";
			if (lista != null || !lista.isEmpty()){
				for (Pais pais : lista) {
					cadena += pais.getName()+", ";
				}
				/* quita la coma y espacio final, o se percibe el mensaje de que no hay pais asignado*/
				cadena += ".";
				cadena = cadena.replace(", .", ""); 
			}
			return cadena;
			
		}

este metodos debe estar en una clase de utilidades

**Comment by Zorben** [comment]
hecho
